### ISSUE TITLE
Adjuster

### ISSUE THREAD

**Issue by LeonaMorro** [HowardBaxton/nPose#33]
I spent a lot of time with adjusting seats. After moving or rotating an adjuster, I have wait up to 2 seconds until the avatar reaches the new position/rotation. I guess adjusters are mostly used during the initial setup and sparly regular. Can we speed up the timer by setting it to ... 0.1s? 0.2s? 0.5s?

**Comment by HowardBaxton** [comment]
Today I tested with a smaller timer in the adjuster prim script.  At 0.1s, each time I asked the adjuster to rez, my seated position was changed to somewhere other than where I should be (different from the adjuster position even).  At the 0.5s timer testing, all seemed to work fine (in my region).

If we change this, I worry we will be opening a door for issues in more laggy regions.  My vote is to leave the 2.0s timer in place.

**Comment by LeonaMorro** [comment]
Of course it should stay at 2.0s if there is a risk of issues. But then we should investigate WHY it does behave like this. I made a pull request to get the Adjuster code into this repo for further investigations and tag this "issue" as TODO (with a very low priority ;) )

**Comment by HowardBaxton** [comment]
1.)  Slave script rezzes each adjuster one at a time at <0,0,.1> from rezing object.
2.)  Slave sends position/rotation from slots list.
3.)  Adjuster hears chat and moves to slot poistion/rotation.
4.)  Timer fires in Adjuster and reports position back to nPose.
5.)  Core moves AV to Adjuster position.

If the timer in the Adjuster fires to quickly, the following happens:
1.)  Slave script rezzes each adjuster one at a time at <0,0,.1> from rezing object.
2.)  Slave sends position/rotation from slots list.
3.)  Timer fires in Adjuster and reports position back to nPose.
4.)  Core moves AV to Adjuster position.
5.)  Adjuster hears chat and moves to slot poistion/rotation.

Av ends up as <0,0,.1> from rezing object.  

Since AV can only move 10 meters from the base and Slave can only rez the Adjuster the same distance, the possibility exists to rez the Adjuster at the proper location for each slot to ensure lag allows the timer to be fired before the listener gets location in this order:
1.)  Slave grabs slot position/rotation.
2.)  Slave rezzes this Adjuster in that position/rotation.
3.)  Timer fires and reports back to core.
4.)  Core moves AV to the adjuster position/rotation.

**Comment by HowardBaxton** [comment]
This issue is addressed in 2 branches actually.  The fix with the smaller scope is "A-change-I-can-live-with"
