### ISSUE TITLE
Gender detection

### ISSUE THREAD

**Issue by HowardBaxton** [HowardBaxton/nPose#38]
LL has added a function to detect gender based upon AV attributes.  Is it possible to reliably predict gender and assign a proper seat?

**Comment by LeonaMorro** [comment]
You mean `OBJECT_BODY_SHAPE_TYPE` which can be used with `llGetObjectDetails`?
It is a Shape parameter, so the question is: Does the shape always reflect the gender of the Avatar?
AFAIK:
- this should work for almost all standart LL Avatars
- this may or may not work for non fitted mesh custom avatars (because you will see no difference wearing a male or female shape) (I don't know if there are much avatars availible that don't use fitted mesh)
- this should work for an huge amount of human fitted mesh custom avatars
- this may or may not work for non human fitted mesh custom avatars (I belive furies are sometimes based on the female shape even if they are males and I can think of many others)

**Comment by HowardBaxton** [comment]
I do agree.  This functionality has been requested and I didn't want to write it off without some discussion.
