### ISSUE TITLE
Normalize Data to eliminate case specificity.

### ISSUE THREAD

**Issue by CertifiedLunasea** [HowardBaxton/nPose#65]
Would it be possible to use llToLower or llToUpper to normalize the data used by nPose and core plugins in a future release?

It would eliminate some user error due to incorrect capitalization of data in notecards since, as it stands, the data is case specific. That being said it is perfectly workable without the normalization.

**Comment by LeonaMorro** [comment]
example:
LINKMSG|4711|A nice string|%AVKEY%
consists of:
The command part|The number part|The string part.|The key part

When we interpret the line 
- we could make the command part case insensitive
- we don't need to do anything to the number part, because it is converted to an integer
- we shouldn't touch the string part because a user may decide to send linkmessages to a third-party script which uses case sensitive data.
- we shouldn't touch the key part, because f.e. %AVKEY% could be used in the string part (which we shouldn't touch) as well as in the key part

So finaly only the command part could/should be touched and I guess that isn't the part you want to have converted?

**Comment by HowardBaxton** [comment]
The current release of nPose does normalize options (the string part).  LINKMSG, (NOT)SATMSG lines are not normalized for the reasons listed above.  I vote this issue be closed.
