### ISSUE TITLE
Add some means to allow builder to add custom text to the menu prompt

### ISSUE THREAD

**Issue by HowardBaxton** [HowardBaxton/nPose#74]
I think this could easily be done by getting notecard description, or via SATMSG line or LINKMSG line.

Further investigation is needed.

**Comment by LeonaMorro** [comment]
That would be nice, but at the time we generate the menu (DoMenu) we even don't know the NC name.

**Comment by LeonaMorro** [comment]
Correct me if I'm wrong: You can't get the description from anything in the inventory of an object?

**Comment by LeonaMorro** [comment]
So if we can't get some text from the NC description, the text for the menu promt have to be read from the NC (as you said f.e. by a LINKMSG). But thats also impossible because of the message flow within the nPose scripts:
![oldmessageflow](https://cloud.githubusercontent.com/assets/11649910/16379286/fcb14f4a-3c70-11e6-96a8-31f653aa1001.png)

To make it possible to influence the menu generation by the content of a NC we have to change the message flow to get rid of the asyncronous behaviour:
![newmessageflow](https://cloud.githubusercontent.com/assets/11649910/16379499/2637d1a8-3c72-11e6-839d-308d3afbd63f.png)

There are some drawbacks but also a bunch of new possibilities in doing so:
Drawbacks
- the menu will not work without the NC Reader and/or Core script (But I guess thats nobody uses the menu without the other two scripts?)
- there will be a delay while opening a menu. The amount of the delay mainly depends on if the content of the NC is cached (almost no delay) or not (~0.1s per NC Line)

Pros
- we will be able to easily inject the text for the menu promt via the NC
- button permissions will work a lot better than currently, which gives us the opportunity to use them for something cool like toggle buttons (much more easily than now)

Well, I guess we should simply test it .. I will make a new branch derived from the "Leona Grouping" branch.

**Comment by LeonaMorro** [comment]
Houston, we have a problem
Currently the Back Button doesn't trigger the execution of a NC. If we want to keep this behaviour, nothing inside a NC could be used to influence the building of the menu (without doing some (dirty?) tricks).
The same happens if the selection doesn't have a child and we simply remenu.

Question:
1) Would it be a no-go if we allow the execution of a NC as a result of using the Back button?
2) Would it be a no-go if we allow the execution of a NC as a result of a remenu operation?

![oldmessageflow1](https://cloud.githubusercontent.com/assets/11649910/16409598/bd032428-3d1e-11e6-9404-5e2d9c585955.png)

**Comment by HowardBaxton** [comment]
Back Button Behavior is a nice option:
Currently when a menu user clicks a sub menu button it is possible to do any action as well as dialog the sub menu.  As you point out leaving that sub menu via back button has no possibility to undo or do something else.  I think this is a nice option to have, even if it is only to run the lead-into action.  The situation could get erratic when menu user attempts to go back button from several menu levels down but there are ways to avoid using the back button and go directly to some other sub menu.  I also believe builders will want to control what happens at each sub menu via back button.
In terms of menu text this is certainly a required option.

Re-menu Operation:
For internal operations such as check boxes and toggle buttons there would be no other way but to use these operations.
For builder intervention and control this would be very difficult to set up and maintain due to the huge number of re-menus that take place.

**Comment by LeonaMorro** [comment]
added in nPose 3.0
