### ISSUE TITLE
Group ChangeSeats by solo/couple or possibly some custom grouping

### ISSUE THREAD

**Issue by HowardBaxton** [HowardBaxton/nPose#75]

**Comment by LeonaMorro** [comment]
Could you explain this a little more? .. Perhaps add one or more examples?

**Comment by LeonaMorro** [comment]
The Example:

When you name the seat it will be in the form of Group:name in each ANIM, SCHMO, SCHMOE line

To call the Group change seat, you will use the following command in a BTN card
`LINKMSG|-889|Group|%AVKEY%`

Added the following lines between 1179 and 1180 in the nPose Menu 2.0 script

``` lsl
        else if(num == -889) {

            integer i = 0;
            string slot;
            integer end = llGetListLength(slotbuttons);
            list newslotbuttons;
            for (; i<end; ++i)
            {
                slot = llList2String(slotbuttons,i);
                integer len = llSubStringIndex(slot, ":")-1;
                if (str == llGetSubString(slot, 0, len)) {
                    newslotbuttons += slot;
                }
            }
            path = path + ":" + "ChangeSeat";
            AdminMenu(id, path,  "Where will you sit?", newslotbuttons);
        }
```

**Comment by LeonaMorro** [comment]
I also have some scenarios that would benefit from a facelifting in the swaping code:

a) nPose in Vehicles, for example a bus: passengers should only be allowed to swap between passenger seats
b) almost the same as a): A bar, with a slots for one or more barkeepers and one or more guests
c) RLV: in some cases a victim may be allowed to swap to other victim seat or even to a "dom" seat

the current swapping code also don't have much options, for example:
an option to
- show only free seats (see #71)
- show only seatnumbers
- show seatnames
- (not) sort the swap menu

The approach from the post above is creative, but it is also a abuse of the seatname and it is not very flexible because it implements a 1:n relationship: one group can contain 0-n slots, but a slot can only be member of 1 group. In Addition you are forced to use the seatname in any ANIM Command.
A few examples for a different aproach:

Grouping by Seatnumbers:

```
GROUP|myFirstGroupName|1~2~3
GROUP|mySecondGroupName|3~4~5
```

Grouping with buildIn Keywords:

```
GROUP|myFirstGroupName|FREE_SEATS
GROUP|mySecondGroupName|RLV_ENABLED_SEATS
```

Combination:

```
GROUP|myFirstGroupName|FREE_SEATS~1
GROUP|mySecondGroupName|1&FREE_SEATS ~ 2&FREE_SEATS ~ 3&FREE_SEATS
GROUP|myThirdGroupName|!FREE_SEATS
```

Separating the Group definition from the ANIM lines makes it also possible to define some Groups by third party scripts on the fly (like the User Defined Permissions)

Groups defined separatly may also be used as a Menu Permission:

Example:

DEFAULT:

```
GROUP|managers|1
GROUP|barkeepers|1~2~3
GROUP|guests|4~5~6~7~8~9
ANIM|...
...
```

SET:Work{[barkeepers]}

```
SCHMO|...
...
```

SET:WorkHarder{[barkeepers] & ![managers]}

```
SCHMO|...
...
```

SET:Relax{[managers]~[guest]}

```
SCHMO|...
...
```

SET:Drink{[guest]}

```
SCHMO|...
...
```

SET:Eat{[guest]}

```
SCHMO|...
...
```

All that means that the Swap menu should be build just in time and in one script and not as it is now in the slave and the menu script on a slot change. I would suggest to do it inside the core (and not inside a separate script) because it seems to be a "must have" feature and there are some functions inside the core that would help us to parse the GROUP definition.

RFC

**Comment by HowardBaxton** [comment]
This comes with the same challenge of getting the change seats menu in
"just in time" fashion.  For swap it can work but for change seats there
are challenges.

Another thing that comes to mind if in the core, this would require
updating all seats.  I do not believe swap currently effects all seats.  I
am not at PC to check for sure.

**Comment by LeonaMorro** [comment]
added in nPose 3.0
