### ISSUE TITLE
Color / Texture Changer

### ISSUE THREAD

**Issue by LeonaMorro** [HowardBaxton/nPose#87]
lvddawter reported: Can't change the color without changing the texture.

The last script I have in my inventory is: nPose Color/Texture rev. .028.06
It seems that the texture UUID is passed by the id part of the linkMessage. In the core we set the id of the linkMessage to the current menu user if no id is supplied in the LINKMSG command. For the Color/Texture changer plugin this means that a invalid texture uuid is supplied if the user don't set a texture uuid inside the LINKMSG.
AFAIR: Didn't Deneby wrote a new Color / Texture Changer script? If yes: we should place a copy on github.

**Comment by HowardBaxton** [comment]
During testing no negative effects were encountered by leaving the texture uuid blank in the LINKMSG.  My uuid was indeed passed but no error was thrown and the color does change as intended.  The test where a texture is added to contents and the name of that texture is supplied works perfectly.

Is it a bug? 
Since there is a chance a non-texture uuid can be passed it could be a bug but where no error is thrown and the script works as intended in all cases, maybe it isn't a bug.

**Comment by LeonaMorro** [comment]
Yes, the color changed without an error, but the texture changes also.
Currently you can't change the color AND KEEP the texture without supplying the texture UUID inside the NC.

**Comment by LeonaMorro** [comment]
@HowardBaxton I send you a Demo called "nPose Color / Texture Changer issue #87"

**Comment by HowardBaxton** [comment]
Thank you.  I've made 2 bad assumptions and did not fully test (obviously).

As for a replacement plugin, several have tried to make a more robust script but they give up because it is too hard.  They have been requested to allow changes to all settings on the Texture tab in the edit screen.

To fix this one issue is easy enough and this plugin will require a change to work with the next release anyway.  I have no problem dealing with this (now that I understand the problem).

**Comment by LeonaMorro** [comment]
This issue doesn't exist in the Prim Param Editor plugin (which is a replacement of the nPose Color/Texture)
